commands:
  list: true
  vanish: true
  nickname: true
  nickreset: true
  color: true
  realname: true
  rename: true
features:
  update-check: true
  join-leave: true
  dynmap-hide: true
  op-see-vanish: true
  motd: true
  qol: true
  night-skip: true
  nickname-length: 16
  chat-formatting: true
  minecartdmg-fix: true
  debug: false
anti-spam:
  enabled: true
  message-limit: 10
  time-window: 10
Version: 2.0
